/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Manager;

import ControllLayer.Manager.ManagerController;
import ControllLayer.ParityCheck;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Malakagl
 */
public class CustNew extends javax.swing.JPanel {

    /**
     * Creates new form CustNew
     */
    public CustNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        txtNewCustName = new javax.swing.JTextField();
        txtNewCustAddCity = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnNewCustCreate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtAddNum = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNewCustAddStrt = new javax.swing.JTextField();
        txtNewCustEmail = new javax.swing.JTextField();
        txtNewCustID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNewCustAddNum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbNewCustType = new javax.swing.JComboBox();
        btnNewCustCancel = new javax.swing.JButton();
        pnlAddTP = new javax.swing.JPanel(new GridLayout(0,1));
        btnAddTP = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtNewCustCreditLimit = new javax.swing.JTextField();
        chkCreditFacAccepted = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        txtNewCustName1 = new javax.swing.JTextField();

        jScrollPane6.setPreferredSize(new java.awt.Dimension(720, 592));

        jPanel3.setPreferredSize(new java.awt.Dimension(700, 490));

        txtNewCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustNameActionPerformed(evt);
            }
        });
        txtNewCustName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewCustNameFocusGained(evt);
            }
        });

        jLabel34.setText("Telephone Number");

        btnNewCustCreate.setText("Create");
        btnNewCustCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustCreateActionPerformed(evt);
            }
        });

        jLabel10.setText("Street");

        jLabel13.setText("Customer Type");

        jLabel9.setText("Number");

        jTxtAddNum.setText("Address");

        jLabel5.setText("Customer ID");

        txtNewCustAddStrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustAddStrtActionPerformed(evt);
            }
        });

        txtNewCustID.setEditable(false);

        jLabel7.setText("First Name");

        txtNewCustAddNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustAddNumActionPerformed(evt);
            }
        });

        jLabel11.setText("City");

        jLabel12.setText("E-mail");

        cmbNewCustType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Mail-Order", "Large Order", "Walk-In VIP" }));
        cmbNewCustType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNewCustTypeItemStateChanged(evt);
            }
        });
        cmbNewCustType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNewCustTypeActionPerformed(evt);
            }
        });

        btnNewCustCancel.setText("Cancel");
        btnNewCustCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustCancelActionPerformed(evt);
            }
        });

        btnAddTP.setText("Add Another Number");
        btnAddTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTPActionPerformed(evt);
            }
        });

        jLabel35.setText("Credit Limit");

        txtNewCustCreditLimit.setEditable(false);

        chkCreditFacAccepted.setText("Credit Facility Accepted");
        chkCreditFacAccepted.setEnabled(false);
        chkCreditFacAccepted.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCreditFacAcceptedItemStateChanged(evt);
            }
        });

        jLabel44.setText("Last Name");

        txtNewCustName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCustName1ActionPerformed(evt);
            }
        });
        txtNewCustName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewCustName1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnNewCustCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNewCustCancel))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtAddNum)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel34))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNewCustEmail)
                                    .addComponent(btnAddTP)
                                    .addComponent(pnlAddTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNewCustAddStrt, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                            .addComponent(txtNewCustAddNum)
                                            .addComponent(txtNewCustAddCity))))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel35))
                            .addGap(49, 49, 49)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbNewCustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNewCustCreditLimit))))
                    .addComponent(chkCreditFacAccepted)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel44))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewCustName, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtNewCustName1))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNewCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNewCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtNewCustName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAddNum)
                    .addComponent(txtNewCustAddNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNewCustAddCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNewCustAddStrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(txtNewCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(pnlAddTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbNewCustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(chkCreditFacAccepted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(txtNewCustCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCustCancel)
                    .addComponent(btnNewCustCreate))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewCustNameActionPerformed

    private void txtNewCustNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewCustNameFocusGained
        // TODO add your handling code here:
        String id = ManagerController.getNewCustomerID();
        txtNewCustID.setText("CU" + id
                + ParityCheck.getKey(id));
    }//GEN-LAST:event_txtNewCustNameFocusGained

    private void btnNewCustCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustCreateActionPerformed
        // TODO add your handling code here:
        String id = txtNewCustID.getText();
        details.add(txtNewCustID.getText().substring(2, id.length() - 1));
        details.add(txtNewCustName.getText());
        details.add(txtNewCustName1.getText());
        details.add(txtNewCustAddStrt.getText());
        details.add(txtNewCustAddCity.getText());
        details.add(txtNewCustAddNum.getText());
        details.add(txtNewCustEmail.getText());
        details.add(((String) cmbNewCustType.getSelectedItem()).charAt(0) + "");
        if (chkCreditFacAccepted.isSelected()
                && !txtNewCustCreditLimit.getText().equals("")) {
            details.add(txtNewCustCreditLimit.getText());
        } else {
            details.add("0");
        }
        for (int i = 0; i < numbers.size(); i++) {
            details.add(((JTextField) numbers.get(i)).getText());
        }

        if (ManagerController.insertCustomer(details) > 0) {
            JOptionPane.showMessageDialog(this, "Customer Inserted "
                    + "Successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong."
                    + "Customer creation was not successful.");
        }

        txtNewCustID.setText("");
        txtNewCustName.setText("");
        txtNewCustName1.setText("");
        txtNewCustAddCity.setText("");
        txtNewCustAddStrt.setText("");
        txtNewCustAddNum.setText("");
        txtNewCustEmail.setText("");
        cmbNewCustType.setSelectedItem(0);
        chkCreditFacAccepted.setSelected(false);
        txtNewCustCreditLimit.setText("");
        numbers = new ArrayList<>();
        details = new ArrayList<>();
        pnlAddTP.removeAll();
        btnAddTP.doClick();
    }//GEN-LAST:event_btnNewCustCreateActionPerformed

    private void txtNewCustAddStrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustAddStrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewCustAddStrtActionPerformed

    private void txtNewCustAddNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustAddNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewCustAddNumActionPerformed

    private void cmbNewCustTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNewCustTypeItemStateChanged
        // TODO add your handling code here:
        if (cmbNewCustType.getSelectedIndex() > 1) {
            chkCreditFacAccepted.setEnabled(true);
        } else {
            chkCreditFacAccepted.setEnabled(false);
        }
    }//GEN-LAST:event_cmbNewCustTypeItemStateChanged

    private void cmbNewCustTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNewCustTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNewCustTypeActionPerformed

    private void btnNewCustCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustCancelActionPerformed
        // TODO add your handling code here:
        txtNewCustID.setText("");
        txtNewCustName.setText("");
        txtNewCustAddCity.setText("");
        txtNewCustAddStrt.setText("");
        txtNewCustAddNum.setText("");
        txtNewCustEmail.setText("");
        cmbNewCustType.setSelectedItem(0);
        cmbNewCustType.setSelectedIndex(0);
        ManagerView.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnNewCustCancelActionPerformed

    private void btnAddTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTPActionPerformed
        // TODO add your handling code here:
        if (numbers.isEmpty()) {
            JTextField temp = new JTextField("");
            temp.setPreferredSize(txtNewCustEmail.getSize());
            numbers.add(temp);
            pnlAddTP.add(temp);
            pnlAddTP.revalidate();
            validate();
        } else if (!((JTextField) numbers.get(numbers.size() - 1)).getText().equals("")) {
            JTextField temp = new JTextField("");
            temp.setPreferredSize(txtNewCustEmail.getSize());
            numbers.add(temp);
            pnlAddTP.add(temp);
            pnlAddTP.revalidate();
            validate();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter the number above.");
        }
    }//GEN-LAST:event_btnAddTPActionPerformed

    private void chkCreditFacAcceptedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCreditFacAcceptedItemStateChanged
        // TODO add your handling code here:
        if (chkCreditFacAccepted.isSelected()) {
            txtNewCustCreditLimit.setEditable(true);
        } else {
            txtNewCustCreditLimit.setEditable(false);
        }
    }//GEN-LAST:event_chkCreditFacAcceptedItemStateChanged

    private void txtNewCustName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCustName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewCustName1ActionPerformed

    private void txtNewCustName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewCustName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewCustName1FocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAddTP;
    private javax.swing.JButton btnNewCustCancel;
    private javax.swing.JButton btnNewCustCreate;
    private javax.swing.JCheckBox chkCreditFacAccepted;
    private javax.swing.JComboBox cmbNewCustType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel jTxtAddNum;
    private javax.swing.JPanel pnlAddTP;
    private javax.swing.JTextField txtNewCustAddCity;
    private javax.swing.JTextField txtNewCustAddNum;
    private javax.swing.JTextField txtNewCustAddStrt;
    private javax.swing.JTextField txtNewCustCreditLimit;
    private javax.swing.JTextField txtNewCustEmail;
    private javax.swing.JTextField txtNewCustID;
    private javax.swing.JTextField txtNewCustName;
    private javax.swing.JTextField txtNewCustName1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Object> details = new ArrayList<>();
    ArrayList<Object> numbers = new ArrayList<>();
}
