/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Manager;

import ControllLayer.Manager.ManagerController;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Malakagl
 */
public class CustSearch extends javax.swing.JPanel {
    private JTable current;

    /**
     * Creates new form CustSearch
     */
    public CustSearch() {
        initComponents();
        LastName.setName("AddressCity");
        AvailableCredit.setName("AvailableCredit");
        CreditLimit.setName("CreditLimit");
        CustomerID.setName("CustomerID");
        Address.setName("CustomerType");
        Email.setName("Email");
        FirstName.setName("FirstName");
        CustType.setName("TelephoneNumber");
        TotalPoint.setName("TotalPoint");  
        LastName.setName("LastName");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbFindCustBy = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtFindCustVal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustomerID = new javax.swing.JCheckBox();
        Email = new javax.swing.JCheckBox();
        LastName = new javax.swing.JCheckBox();
        FirstName = new javax.swing.JCheckBox();
        Address = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFindCust = new javax.swing.JTable();
        CustType = new javax.swing.JCheckBox();
        btnFindCustCancel = new javax.swing.JButton();
        CreditLimit = new javax.swing.JCheckBox();
        AvailableCredit = new javax.swing.JCheckBox();
        TotalPoint = new javax.swing.JCheckBox();
        Telephone = new javax.swing.JCheckBox();
        btnFindCustFind = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(300, 400));

        jLabel2.setText("Find Customer by ");

        cmbFindCustBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "CustomerID", "FirstName", "AddressCity", "AddressStreet", "Email", "CustomerType", "TelephoneNumber" }));

        jLabel3.setText("Value searching for ");

        txtFindCustVal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFindCustValFocusGained(evt);
            }
        });

        jLabel4.setText("Show me ");

        CustomerID.setSelected(true);
        CustomerID.setText("Customer ID");
        CustomerID.setEnabled(false);
        CustomerID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CustomerIDItemStateChanged(evt);
            }
        });

        Email.setSelected(true);
        Email.setText("Email");
        Email.setEnabled(false);
        Email.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EmailItemStateChanged(evt);
            }
        });

        LastName.setSelected(true);
        LastName.setText("Last Name");
        LastName.setEnabled(false);
        LastName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LastNameItemStateChanged(evt);
            }
        });

        FirstName.setSelected(true);
        FirstName.setText("First Name");
        FirstName.setEnabled(false);
        FirstName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FirstNameItemStateChanged(evt);
            }
        });

        Address.setSelected(true);
        Address.setText("Address");
        Address.setEnabled(false);
        Address.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AddressItemStateChanged(evt);
            }
        });

        jScrollPane2.setViewportView(tableFindCust);

        CustType.setSelected(true);
        CustType.setText("Customer Type");
        CustType.setEnabled(false);
        CustType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CustTypeItemStateChanged(evt);
            }
        });

        btnFindCustCancel.setText("Cancel");
        btnFindCustCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustCancelActionPerformed(evt);
            }
        });

        CreditLimit.setSelected(true);
        CreditLimit.setText("Credit Limit");
        CreditLimit.setEnabled(false);
        CreditLimit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CreditLimitItemStateChanged(evt);
            }
        });

        AvailableCredit.setSelected(true);
        AvailableCredit.setText("Available credit");
        AvailableCredit.setEnabled(false);
        AvailableCredit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AvailableCreditItemStateChanged(evt);
            }
        });

        TotalPoint.setSelected(true);
        TotalPoint.setText("Total Point");
        TotalPoint.setEnabled(false);
        TotalPoint.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TotalPointItemStateChanged(evt);
            }
        });

        Telephone.setSelected(true);
        Telephone.setText("Telephone");
        Telephone.setEnabled(false);
        Telephone.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TelephoneItemStateChanged(evt);
            }
        });

        btnFindCustFind.setText("Find");
        btnFindCustFind.setEnabled(false);
        btnFindCustFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AvailableCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Telephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TotalPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreditLimit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CustType, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(169, 169, 169))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(542, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFindCustBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(95, 95, 95)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addComponent(txtFindCustVal))
                .addGap(106, 106, 106)
                .addComponent(btnFindCustFind, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(531, 531, 531)
                .addComponent(btnFindCustCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFindCustFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbFindCustBy)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindCustVal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CustomerID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvailableCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreditLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFindCustCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindCustValFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindCustValFocusGained
        // TODO add your handling code here:
        btnFindCustFind.setEnabled(true);
    }//GEN-LAST:event_txtFindCustValFocusGained

    private void EmailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EmailItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_EmailItemStateChanged

    private void LastNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LastNameItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_LastNameItemStateChanged

    private void AddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AddressItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_AddressItemStateChanged

    private void btnFindCustFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustFindActionPerformed
        // TODO add your handling code here:
        if (txtFindCustVal.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a value to "
                + "do search.");
            return;
        }

        Object[] conditions = new Object[2];
        conditions[0] = cmbFindCustBy.getSelectedItem();
        conditions[1] = txtFindCustVal.getText();

        JTable table = ManagerController.getSearchResult(conditions);
        current = new JTable(table.getModel());

        if (table == null || table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No result found.");
        } else {
            LastName.setEnabled(true);
            CustomerID.setEnabled(true);
            Email.setEnabled(true);
            FirstName.setEnabled(true);
            Address.setEnabled(true);
            AvailableCredit.setEnabled(true);
            TotalPoint.setEnabled(true);
            CreditLimit.setEnabled(true);
            CustType.setEnabled(true);
            Telephone.setEnabled(true);
            tableFindCust.setModel(table.getModel());
        }
    }//GEN-LAST:event_btnFindCustFindActionPerformed

    private void CustTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CustTypeItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_CustTypeItemStateChanged

    private void btnFindCustCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindCustCancelActionPerformed

    private void CreditLimitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CreditLimitItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_CreditLimitItemStateChanged

    private void AvailableCreditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AvailableCreditItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_AvailableCreditItemStateChanged

    private void TotalPointItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TotalPointItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_TotalPointItemStateChanged

    private void TelephoneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TelephoneItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_TelephoneItemStateChanged

    private void CustomerIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CustomerIDItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_CustomerIDItemStateChanged

    private void FirstNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FirstNameItemStateChanged
        // TODO add your handling code here:
        refresh(evt);
    }//GEN-LAST:event_FirstNameItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Address;
    private javax.swing.JCheckBox AvailableCredit;
    private javax.swing.JCheckBox CreditLimit;
    private javax.swing.JCheckBox CustType;
    private javax.swing.JCheckBox CustomerID;
    private javax.swing.JCheckBox Email;
    private javax.swing.JCheckBox FirstName;
    private javax.swing.JCheckBox LastName;
    private javax.swing.JCheckBox Telephone;
    private javax.swing.JCheckBox TotalPoint;
    private javax.swing.JButton btnFindCustCancel;
    private javax.swing.JButton btnFindCustFind;
    private javax.swing.JComboBox cmbFindCustBy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableFindCust;
    private javax.swing.JTextField txtFindCustVal;
    // End of variables declaration//GEN-END:variables
    ArrayList<Object> details = new ArrayList<>();
    ArrayList<Object> numbers = new ArrayList<>();
    ArrayList<String> users = new ArrayList<>();

    private void refresh(ItemEvent evt) {
        if (evt.getStateChange() == 2) {
            details.add(((JCheckBox) evt.getSource()).getName());
        } else {
            details.remove(((JCheckBox) evt.getSource()).getName());
        }
        tableFindCust.setModel(ManagerController.refreshTable(current, details));
    }
}
