/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Manager;

import ControllLayer.Manager.ManagerController;
import javax.swing.JOptionPane;

/**
 *
 * @author Malakagl
 */
public class CustEdit extends javax.swing.JPanel {

    /**
     * Creates new form CustEdit
     */
    public CustEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnEditCustCancel = new javax.swing.JButton();
        txtEditCustEmail = new javax.swing.JTextField();
        btnEditCustUpdate = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cmbEditCustType = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        txtEditCustAddStrt = new javax.swing.JTextField();
        txtEditCustName = new javax.swing.JTextField();
        jTxtAddNum1 = new javax.swing.JLabel();
        txtEditCustCity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnEditCustSearch = new javax.swing.JButton();
        txtEditCustCustID = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtEditCustTP2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEditCustAddNum = new javax.swing.JTextField();
        txtEditCustTP1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEditCustID = new javax.swing.JTextField();

        btnEditCustCancel.setText("Cancel");
        btnEditCustCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustCancelActionPerformed(evt);
            }
        });

        btnEditCustUpdate.setText("Update");
        btnEditCustUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustUpdateActionPerformed(evt);
            }
        });

        jLabel30.setText("Customer Type");

        jLabel33.setText("Number");

        cmbEditCustType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Mail-Order", "Long Term", "Walk-In VIP" }));
        cmbEditCustType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEditCustTypeItemStateChanged(evt);
            }
        });

        jLabel31.setText("City");

        txtEditCustName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEditCustNameFocusGained(evt);
            }
        });

        jTxtAddNum1.setText("Address");

        jLabel29.setText("E-mail");

        jLabel28.setText("Name");

        jLabel36.setText("Telephone Number");

        btnEditCustSearch.setText("Search");
        btnEditCustSearch.setEnabled(false);
        btnEditCustSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustSearchActionPerformed(evt);
            }
        });

        txtEditCustCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditCustCustIDActionPerformed(evt);
            }
        });
        txtEditCustCustID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEditCustCustIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEditCustCustIDFocusLost(evt);
            }
        });

        jLabel32.setText("Street");

        jLabel6.setText("Customer ID");

        txtEditCustTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditCustTP1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Telephone Number 2");

        jLabel15.setText("Enter Customer ID");

        txtEditCustID.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtEditCustCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditCustSearch))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel28)
                                    .addComponent(jTxtAddNum1)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditCustTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbEditCustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(btnEditCustUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnEditCustCancel))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditCustCity, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditCustAddStrt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtEditCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEditCustName)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEditCustAddNum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtEditCustEmail)
                                        .addComponent(txtEditCustTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEditCustCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCustSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtEditCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAddNum1)
                    .addComponent(txtEditCustAddNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditCustAddStrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditCustCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(txtEditCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(txtEditCustTP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditCustTP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cmbEditCustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditCustCancel)
                    .addComponent(btnEditCustUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditCustCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustCancelActionPerformed
        // TODO add your handling code here:
        ManagerView.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnEditCustCancelActionPerformed

    private void btnEditCustUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustUpdateActionPerformed
        // TODO add your handling code here:
        String[] details = new String[7];
        details[0] = txtEditCustID.getText();
        details[1] = txtEditCustName.getText();
        details[2] = txtEditCustCity.getText();
        details[5] = txtEditCustEmail.getText();
        details[3] = txtEditCustAddStrt.getText();
        details[4] = txtEditCustAddNum.getText();
        details[6] = ((String) cmbEditCustType.getSelectedItem()).charAt(0) + "";

        if (ManagerController.updateCust(details)) {
            JOptionPane.showMessageDialog(this, "Customer Details Updated "
                + "Successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong."
                + "Update was not successful.");
        }
    }//GEN-LAST:event_btnEditCustUpdateActionPerformed

    private void cmbEditCustTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEditCustTypeItemStateChanged
        // TODO add your handling code here:
        switch (cmbEditCustType.getSelectedIndex()) {
            case 1:
            // create a Mail Order
            break;
            case 2:
            // create a Long term Customer
            break;
            case 3:
            // create a walk in VIP
            break;
        }
    }//GEN-LAST:event_cmbEditCustTypeItemStateChanged

    private void txtEditCustNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditCustNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditCustNameFocusGained

    private void btnEditCustSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustSearchActionPerformed
        // TODO add your handling code here:
        String id = txtEditCustCustID.getText();
        String[] details = ManagerController.getCustomerDetails(id);
        if (details != null) {
            txtEditCustID.setText(details[0]);
            txtEditCustName.setText(details[1]);
            txtEditCustCity.setText(details[2]);
            txtEditCustEmail.setText(details[5]);
            txtEditCustAddStrt.setText(details[3]);
            txtEditCustAddNum.setText(details[4]);
            switch (details[6]) {
                case "M":
                cmbEditCustType.setSelectedIndex(1);
                break;
                case "L":
                cmbEditCustType.setSelectedIndex(2);
                break;
                case "W":
                cmbEditCustType.setSelectedIndex(3);
                break;
            }
            btnEditCustUpdate.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "No details found on this ID.");
        }
    }//GEN-LAST:event_btnEditCustSearchActionPerformed

    private void txtEditCustCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditCustCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditCustCustIDActionPerformed

    private void txtEditCustCustIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditCustCustIDFocusGained
        // TODO add your handling code here:
        btnEditCustSearch.setEnabled(true);
    }//GEN-LAST:event_txtEditCustCustIDFocusGained

    private void txtEditCustCustIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditCustCustIDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditCustCustIDFocusLost

    private void txtEditCustTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditCustTP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditCustTP1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCustCancel;
    private javax.swing.JButton btnEditCustSearch;
    private javax.swing.JButton btnEditCustUpdate;
    private javax.swing.JComboBox cmbEditCustType;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jTxtAddNum1;
    private javax.swing.JTextField txtEditCustAddNum;
    private javax.swing.JTextField txtEditCustAddStrt;
    private javax.swing.JTextField txtEditCustCity;
    private javax.swing.JTextField txtEditCustCustID;
    private javax.swing.JTextField txtEditCustEmail;
    private javax.swing.JTextField txtEditCustID;
    private javax.swing.JTextField txtEditCustName;
    private javax.swing.JTextField txtEditCustTP1;
    private javax.swing.JTextField txtEditCustTP2;
    // End of variables declaration//GEN-END:variables
}
