/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Manager;

import ControllLayer.Manager.ManagerController;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Malakagl
 */
public class ItemSearch extends javax.swing.JPanel {

    /**
     * Creates new form ItemSearch
     */
    public ItemSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        chkBoxLID = new javax.swing.JCheckBox();
        chkBoxBPrc1 = new javax.swing.JCheckBox();
        txtSearchVal1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        chkBoxAvlQty1 = new javax.swing.JCheckBox();
        chkBoxItemCode = new javax.swing.JCheckBox();
        chkBoxLBQty = new javax.swing.JCheckBox();
        cmbSearchItmBy = new javax.swing.JComboBox();
        jScrollPane9 = new javax.swing.JScrollPane();
        ItemDetails = new javax.swing.JTable();
        chkBoxSize = new javax.swing.JCheckBox();
        chkBoxDes = new javax.swing.JCheckBox();
        chkBoxSPrc = new javax.swing.JCheckBox();
        jButton14 = new javax.swing.JButton();
        chkBoxItemTypeName = new javax.swing.JCheckBox();
        chkBoxBrandName = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        chkBoxLID.setText("Last intake date");
        chkBoxLID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxLIDActionPerformed(evt);
            }
        });

        chkBoxBPrc1.setText("Buying price");

        txtSearchVal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchVal1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Show me");

        chkBoxAvlQty1.setText("Available quantity");

        chkBoxItemCode.setSelected(true);
        chkBoxItemCode.setText("Item code");

        chkBoxLBQty.setText("Last buying quantity");

        cmbSearchItmBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "ItemCode", "ItemTypeName", "BrandName", "AvailableQuantity", "BuyingPrice", "SellingPrice", "Size" }));

        ItemDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(ItemDetails);

        chkBoxSize.setText("Size");
        chkBoxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxSizeActionPerformed(evt);
            }
        });

        chkBoxDes.setText("Description");

        chkBoxSPrc.setText("Selling price");

        jButton14.setText("Search");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        chkBoxItemTypeName.setSelected(true);
        chkBoxItemTypeName.setText("Item type name");

        chkBoxBrandName.setText("Brand name");

        jLabel26.setText("Value searching for");

        jLabel25.setText("Search Item by");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(chkBoxItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))
                                    .addComponent(chkBoxDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBoxItemTypeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(chkBoxSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(56, 56, 56)))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkBoxSPrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(54, 54, 54)
                                .addComponent(chkBoxLID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkBoxLBQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(chkBoxAvlQty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkBoxBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56)
                                .addComponent(chkBoxBPrc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSearchItmBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchVal1)
                                .addGap(126, 126, 126))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(464, 464, 464)
                                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(cmbSearchItmBy)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtSearchVal1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(3, 3, 3))
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chkBoxItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxItemTypeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxBPrc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBoxLID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxLBQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxSPrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxAvlQty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBoxDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBoxSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxLIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxLIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxLIDActionPerformed

    private void txtSearchVal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchVal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchVal1ActionPerformed

    private void chkBoxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxSizeActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

        Object[] conditions = new Object[12];
        switch (cmbSearchItmBy.getSelectedIndex()) {
            case 0:
            JOptionPane.showMessageDialog(this, "Please select a value "
                + "type to find.");
            return;

            case 1:
            conditions[0] = "ItemCode";
            break;
            case 2:
            conditions[0] = "ItemTypeName";
            break;
            case 3:
            conditions[0] = "BrandName";
            break;
            case 4:
            conditions[0] = "AvailableQty";
            break;
            case 5:
            conditions[0] = "BuyingPrice";
            break;
            case 6:
            conditions[0] = "SellingPrice";
            break;
            case 7:
            conditions[0] = "Size";
            break;
        }
        conditions[1] = txtSearchVal1.getText();

        conditions[2] = chkBoxItemCode.isSelected();
        conditions[3] = chkBoxItemTypeName.isSelected();
        conditions[4] = chkBoxBrandName.isSelected();
        conditions[5] = chkBoxBPrc1.isSelected();
        conditions[6] = chkBoxSPrc.isSelected();
        conditions[7] = chkBoxLID.isSelected();
        conditions[8] = chkBoxLBQty.isSelected();
        conditions[9] = chkBoxAvlQty1.isSelected();
        conditions[10] = chkBoxDes.isSelected();
        conditions[11]=chkBoxSize.isSelected();

        JTable table = ManagerController.getTable(conditions);

        if (table == null || table.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No result found.");
        }
        ItemDetails.setModel(table.getModel());
    }//GEN-LAST:event_jButton14ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ItemDetails;
    private javax.swing.JCheckBox chkBoxAvlQty1;
    private javax.swing.JCheckBox chkBoxBPrc1;
    private javax.swing.JCheckBox chkBoxBrandName;
    private javax.swing.JCheckBox chkBoxDes;
    private javax.swing.JCheckBox chkBoxItemCode;
    private javax.swing.JCheckBox chkBoxItemTypeName;
    private javax.swing.JCheckBox chkBoxLBQty;
    private javax.swing.JCheckBox chkBoxLID;
    private javax.swing.JCheckBox chkBoxSPrc;
    private javax.swing.JCheckBox chkBoxSize;
    private javax.swing.JComboBox cmbSearchItmBy;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField txtSearchVal1;
    // End of variables declaration//GEN-END:variables
}
