/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Manager;

/**
 *
 * @author Malakagl
 */
public class RepFind extends javax.swing.JPanel {

    /**
     * Creates new form RepFind
     */
    public RepFind() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        chkBoxFindRepTP = new javax.swing.JCheckBox();
        chkBoxFindRepEmail = new javax.swing.JCheckBox();
        chkBoxFindRepName = new javax.swing.JCheckBox();
        chkBoxFindRepType = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        btnFindRepCancel = new javax.swing.JButton();
        btnFindRepFind = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        cmbFindRepBy = new javax.swing.JComboBox();
        txtFindRepVal = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        chkBoxFindRepCity = new javax.swing.JCheckBox();
        chkBoxFindRepID = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        SalesRepDetails = new javax.swing.JTable();

        chkBoxFindRepTP.setSelected(true);
        chkBoxFindRepTP.setText("Telephone");

        chkBoxFindRepEmail.setSelected(true);
        chkBoxFindRepEmail.setText("Email");

        chkBoxFindRepName.setSelected(true);
        chkBoxFindRepName.setText("Name");

        chkBoxFindRepType.setSelected(true);
        chkBoxFindRepType.setText("Sales Rep Type");
        chkBoxFindRepType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxFindRepTypeActionPerformed(evt);
            }
        });

        jLabel50.setText("Show me ");

        btnFindRepCancel.setText("Cancel");
        btnFindRepCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindRepCancelActionPerformed(evt);
            }
        });

        btnFindRepFind.setText("Find");
        btnFindRepFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindRepFindActionPerformed(evt);
            }
        });

        jLabel49.setText("Value searching for ");

        cmbFindRepBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Customer ID", "Name", "City", "Street", "Email", "Customer Type" }));

        jLabel48.setText("Find Sales Rep by ");

        chkBoxFindRepCity.setSelected(true);
        chkBoxFindRepCity.setText("City");
        chkBoxFindRepCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxFindRepCityActionPerformed(evt);
            }
        });

        chkBoxFindRepID.setSelected(true);
        chkBoxFindRepID.setText("Sales Rep ID");

        jScrollPane5.setViewportView(SalesRepDetails);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFindRepBy, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFindRepVal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(chkBoxFindRepID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkBoxFindRepName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkBoxFindRepCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkBoxFindRepEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkBoxFindRepType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkBoxFindRepTP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addComponent(btnFindRepFind))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFindRepCancel)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(cmbFindRepBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(txtFindRepVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBoxFindRepID)
                    .addComponent(chkBoxFindRepType)
                    .addComponent(chkBoxFindRepEmail)
                    .addComponent(chkBoxFindRepCity)
                    .addComponent(chkBoxFindRepName)
                    .addComponent(btnFindRepFind)
                    .addComponent(chkBoxFindRepTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFindRepCancel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxFindRepTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxFindRepTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxFindRepTypeActionPerformed

    private void btnFindRepCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindRepCancelActionPerformed
        // TODO add your handling code here:
        ManagerView.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnFindRepCancelActionPerformed

    private void btnFindRepFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindRepFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindRepFindActionPerformed

    private void chkBoxFindRepCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxFindRepCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxFindRepCityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SalesRepDetails;
    private javax.swing.JButton btnFindRepCancel;
    private javax.swing.JButton btnFindRepFind;
    private javax.swing.JCheckBox chkBoxFindRepCity;
    private javax.swing.JCheckBox chkBoxFindRepEmail;
    private javax.swing.JCheckBox chkBoxFindRepID;
    private javax.swing.JCheckBox chkBoxFindRepName;
    private javax.swing.JCheckBox chkBoxFindRepTP;
    private javax.swing.JCheckBox chkBoxFindRepType;
    private javax.swing.JComboBox cmbFindRepBy;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField txtFindRepVal;
    // End of variables declaration//GEN-END:variables
}
