/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Manager;

import ControllLayer.Manager.ManagerController;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Malakagl
 */
public class RepNew extends javax.swing.JPanel {

    /**
     * Creates new form RepNew
     */
    public RepNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        txtNewRepID = new javax.swing.JTextField();
        btnNewRepCancel = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtNewRepName = new javax.swing.JTextField();
        pnlAddTPSRep = new javax.swing.JPanel(new GridLayout(0,1));
        jLabel60 = new javax.swing.JLabel();
        btnAddTPSRep = new javax.swing.JButton();
        txtNewRepName1 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        txtNewRepID.setEditable(false);

        btnNewRepCancel.setText("Cancel");
        btnNewRepCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRepCancelActionPerformed(evt);
            }
        });

        jLabel51.setText("Sales Rep ID");

        jLabel52.setText("First Name");

        txtNewRepName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRepNameActionPerformed(evt);
            }
        });
        txtNewRepName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewRepNameFocusGained(evt);
            }
        });

        jLabel60.setText("Telephone Number");

        btnAddTPSRep.setText("Add Another Number");
        btnAddTPSRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTPSRepActionPerformed(evt);
            }
        });

        txtNewRepName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRepName1ActionPerformed(evt);
            }
        });
        txtNewRepName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewRepName1FocusGained(evt);
            }
        });

        jLabel65.setText("Last Name");

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel65)
                            .addComponent(jLabel60))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewRepID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewRepName)
                            .addComponent(txtNewRepName1)
                            .addComponent(btnAddTPSRep)
                            .addComponent(pnlAddTPSRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNewRepCancel)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(txtNewRepID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txtNewRepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(txtNewRepName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addComponent(pnlAddTPSRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnAddTPSRep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewRepCancel)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jScrollPane8.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRepCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRepCancelActionPerformed
        // TODO add your handling code here:
        ManagerView.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnNewRepCancelActionPerformed

    private void txtNewRepNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRepNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRepNameActionPerformed

    private void txtNewRepNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewRepNameFocusGained
        // TODO add your handling code here:
        txtNewRepID.setText(ManagerController.getNewSRepID());
    }//GEN-LAST:event_txtNewRepNameFocusGained

    private void btnAddTPSRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTPSRepActionPerformed
        // TODO add your handling code here:
        if (numbers.isEmpty()) {
            JTextField temp = new JTextField("");
            temp.setPreferredSize(txtNewRepName1.getSize());
            numbers.add(temp);
            pnlAddTPSRep.add(temp);
            pnlAddTPSRep.revalidate();
            validate();
        } else if (!((JTextField) numbers.get(numbers.size() - 1)).getText().equals("")) {
            JTextField temp = new JTextField("");
            temp.setPreferredSize(txtNewRepName1.getSize());
            numbers.add(temp);
            pnlAddTPSRep.add(temp);
            pnlAddTPSRep.revalidate();
            validate();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter the number above.");
        }
    }//GEN-LAST:event_btnAddTPSRepActionPerformed

    private void txtNewRepName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRepName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRepName1ActionPerformed

    private void txtNewRepName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewRepName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRepName1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        details.add(txtNewRepID.getText());
        details.add(txtNewRepName.getText());
        details.add(txtNewRepName1.getText());

        for (int i = 0; i < numbers.size(); i++) {
            details.add(((JTextField) numbers.get(i)).getText());
        }

        if (ManagerController.insertSalesRep(details) > 0) {
            JOptionPane.showMessageDialog(this, "Sales Rep was created "
                + "Successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong."
                + "Sales Rep creation was not successful.");
        }

        txtNewRepID.setText("");
        txtNewRepName.setText("");
        txtNewRepName1.setText("");
        numbers = new ArrayList<>();
        details = new ArrayList<>();
        pnlAddTPSRep.removeAll();
        btnAddTPSRep.doClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAddTPSRep;
    private javax.swing.JButton btnNewRepCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlAddTPSRep;
    private javax.swing.JTextField txtNewRepID;
    private javax.swing.JTextField txtNewRepName;
    private javax.swing.JTextField txtNewRepName1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Object> details = new ArrayList<>();
    ArrayList<Object> numbers = new ArrayList<>();
    ArrayList<String> users = new ArrayList<>();
}
