/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer.Cashier;

import ControllLayer.Cashier.Pay_by_cash_controller.amount_text_fieldActionListener;
import ControllLayer.Cashier.Pay_by_cash_controller.finish_buttonActionListener;
import ControllLayer.Cashier.Pay_by_credit_facility_controller.amount_text_field1ActionListener;
import ControllLayer.Cashier.Pay_by_credit_facility_controller.finish_button1ActionListener;
import DataLayer.ConnectCashier;
import com.alee.laf.WebLookAndFeel;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import onestopshop.LogIn;

/**
 *
 * @author Rajind
 */
public class CashierView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CashierView() {
        initComponents();
        postInit();
        this.setVisible(true);
    }
    public void postInit(){
        amount_text_fieldActionListener l = new amount_text_fieldActionListener(this);
        amount_text_field.addActionListener(l);
        
        finish_buttonActionListener l2 = new finish_buttonActionListener(this);
        finish_pay_by_cash_button.addActionListener(l2);
        
        amount_text_field1ActionListener l3 = new amount_text_field1ActionListener(this);
        amount_text_field1.addActionListener(l3);
        
        finish_button1ActionListener l4 = new finish_button1ActionListener(this);
        finish_pay_by_cash_button1.addActionListener(l4);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        home_panel = new javax.swing.JPanel();
        monthly_report_button = new javax.swing.JButton();
        pay_by_cash_button = new javax.swing.JButton();
        pay_by_credit_facility_button = new javax.swing.JButton();
        return_items_button = new javax.swing.JButton();
        recharge_credit_facility_button = new javax.swing.JButton();
        daily_report_button = new javax.swing.JButton();
        history_button = new javax.swing.JButton();
        pay_by_cash_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        print_pay_by_cash_bill = new javax.swing.JButton();
        amount_text_field = new javax.swing.JFormattedTextField();
        total_text_field = new javax.swing.JFormattedTextField();
        item_code_text_field = new javax.swing.JFormattedTextField();
        finish_pay_by_cash_button = new javax.swing.JButton();
        pay_by_credit_facility_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        print_pay_by_cash_bill1 = new javax.swing.JButton();
        finish_pay_by_cash_button1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        total_text_field1 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        amount_text_field1 = new javax.swing.JFormattedTextField();
        item_code_text_field1 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        return_item_panel = new javax.swing.JPanel();
        daily_report_panel = new javax.swing.JPanel();
        monthly_report_panel = new javax.swing.JPanel();
        history_panel = new javax.swing.JPanel();
        recharge_credit_facility_panel = new javax.swing.JPanel();
        customer_id_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        amount_paid_label = new javax.swing.JLabel();
        amount_paid_text_field = new javax.swing.JTextField();
        update_credit_facility_button = new javax.swing.JButton();
        customer_id_text_field = new javax.swing.JFormattedTextField();
        notification_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        notification_label = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(51, 153, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        monthly_report_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/reports.png"))); // NOI18N
        monthly_report_button.setText("Monthly Report");
        monthly_report_button.setToolTipText("Press this button to go to monthly report window");
        monthly_report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthly_report_buttonActionPerformed(evt);
            }
        });

        pay_by_cash_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/money-icon.png"))); // NOI18N
        pay_by_cash_button.setText("Pay by Cash");
        pay_by_cash_button.setToolTipText("Press this button to go to the pay by cash billing window");
        pay_by_cash_button.setIconTextGap(20);
        pay_by_cash_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_by_cash_buttonActionPerformed(evt);
            }
        });

        pay_by_credit_facility_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/103323-3d-glossy-green-orb-icon-business-creditcard2.png"))); // NOI18N
        pay_by_credit_facility_button.setText("Pay by Credit Facility");
        pay_by_credit_facility_button.setToolTipText("Press this button to go to the pay by credit facility billing window");
        pay_by_credit_facility_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_by_credit_facility_buttonActionPerformed(evt);
            }
        });

        return_items_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/Return.png"))); // NOI18N
        return_items_button.setText("Return Items");
        return_items_button.setToolTipText("Press this button to go to item return window");
        return_items_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_items_buttonActionPerformed(evt);
            }
        });

        recharge_credit_facility_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/currency_dollar blue.png"))); // NOI18N
        recharge_credit_facility_button.setText("Recharge Credit Facility");
        recharge_credit_facility_button.setToolTipText("Press this button to go to the recharge credit facility window");
        recharge_credit_facility_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recharge_credit_facility_buttonActionPerformed(evt);
            }
        });

        daily_report_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/report-icon.gif"))); // NOI18N
        daily_report_button.setText("Daily Report");
        daily_report_button.setToolTipText("Press this button to go to daily report window");
        daily_report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daily_report_buttonActionPerformed(evt);
            }
        });

        history_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cashier/history.png"))); // NOI18N
        history_button.setText("History");
        history_button.setToolTipText("Press this button to go to order history window");
        history_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(return_items_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthly_report_button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recharge_credit_facility_button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_by_cash_button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pay_by_credit_facility_button, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daily_report_button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(history_button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        home_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {daily_report_button, history_button, monthly_report_button, pay_by_cash_button, pay_by_credit_facility_button, recharge_credit_facility_button, return_items_button});

        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay_by_cash_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_by_credit_facility_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_report_button)
                    .addComponent(recharge_credit_facility_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthly_report_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(history_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(return_items_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        home_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {monthly_report_button, pay_by_cash_button, recharge_credit_facility_button, return_items_button});

        home_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {daily_report_button, history_button, pay_by_credit_facility_button});

        jTabbedPane1.addTab("Home", home_panel);

        jLabel5.setText("ItemCode");

        jLabel6.setText("Amount");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "Type", "Amount", "Cost per item", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setText("Total");

        print_pay_by_cash_bill.setText("Print");
        print_pay_by_cash_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_pay_by_cash_billActionPerformed(evt);
            }
        });

        amount_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        amount_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_text_fieldActionPerformed(evt);
            }
        });

        total_text_field.setEditable(false);
        total_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        total_text_field.setText("Rs. 0.00");

        try {
            item_code_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU#####UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        item_code_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_code_text_fieldActionPerformed(evt);
            }
        });

        finish_pay_by_cash_button.setText("Finish");
        finish_pay_by_cash_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_pay_by_cash_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pay_by_cash_panelLayout = new javax.swing.GroupLayout(pay_by_cash_panel);
        pay_by_cash_panel.setLayout(pay_by_cash_panelLayout);
        pay_by_cash_panelLayout.setHorizontalGroup(
            pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pay_by_cash_panelLayout.createSequentialGroup()
                .addGroup(pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pay_by_cash_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pay_by_cash_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item_code_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amount_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pay_by_cash_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(print_pay_by_cash_bill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finish_pay_by_cash_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pay_by_cash_panelLayout.setVerticalGroup(
            pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_by_cash_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(amount_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(item_code_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(pay_by_cash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(print_pay_by_cash_bill)
                    .addComponent(total_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finish_pay_by_cash_button)))
        );

        jTabbedPane1.addTab("Pay by Cash", pay_by_cash_panel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "Type", "Amount", "Cost per item", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        print_pay_by_cash_bill1.setText("Print");
        print_pay_by_cash_bill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_pay_by_cash_bill1ActionPerformed(evt);
            }
        });

        finish_pay_by_cash_button1.setText("Finish");
        finish_pay_by_cash_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_pay_by_cash_button1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Total");

        total_text_field1.setEditable(false);
        total_text_field1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        total_text_field1.setText("Rs. 0.00");

        jLabel9.setText("Amount");

        amount_text_field1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        amount_text_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_text_field1ActionPerformed(evt);
            }
        });

        try {
            item_code_text_field1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU#####UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        item_code_text_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_code_text_field1ActionPerformed(evt);
            }
        });

        jLabel10.setText("ItemCode");

        javax.swing.GroupLayout pay_by_credit_facility_panelLayout = new javax.swing.GroupLayout(pay_by_credit_facility_panel);
        pay_by_credit_facility_panel.setLayout(pay_by_credit_facility_panelLayout);
        pay_by_credit_facility_panelLayout.setHorizontalGroup(
            pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pay_by_credit_facility_panelLayout.createSequentialGroup()
                .addGroup(pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pay_by_credit_facility_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pay_by_credit_facility_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item_code_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amount_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pay_by_credit_facility_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(print_pay_by_cash_bill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finish_pay_by_cash_button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pay_by_credit_facility_panelLayout.setVerticalGroup(
            pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_by_credit_facility_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(amount_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(item_code_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(pay_by_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(print_pay_by_cash_bill1)
                    .addComponent(total_text_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finish_pay_by_cash_button1)))
        );

        jTabbedPane1.addTab("Pay by CreditFacility", pay_by_credit_facility_panel);
        jTabbedPane1.addTab("Return Item", return_item_panel);
        jTabbedPane1.addTab("Daily Report", daily_report_panel);
        jTabbedPane1.addTab("Monthly Report", monthly_report_panel);
        jTabbedPane1.addTab("History", history_panel);

        customer_id_label.setText("CustomerID");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        amount_paid_label.setText("Amount Paid");

        update_credit_facility_button.setText("Update");
        update_credit_facility_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_credit_facility_buttonActionPerformed(evt);
            }
        });

        try {
            customer_id_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        customer_id_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_id_text_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recharge_credit_facility_panelLayout = new javax.swing.GroupLayout(recharge_credit_facility_panel);
        recharge_credit_facility_panel.setLayout(recharge_credit_facility_panelLayout);
        recharge_credit_facility_panelLayout.setHorizontalGroup(
            recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                        .addComponent(customer_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_id_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(amount_paid_label)
                        .addGap(18, 18, 18)
                        .addGroup(recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount_paid_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(update_credit_facility_button))))))
        );
        recharge_credit_facility_panelLayout.setVerticalGroup(
            recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_id_label)
                    .addComponent(customer_id_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(recharge_credit_facility_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount_paid_label)
                            .addGroup(recharge_credit_facility_panelLayout.createSequentialGroup()
                                .addComponent(amount_paid_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update_credit_facility_button))))))
        );

        jTabbedPane1.addTab("Recharge Credit Facility", recharge_credit_facility_panel);

        notification_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Notifications:");

        javax.swing.GroupLayout notification_panelLayout = new javax.swing.GroupLayout(notification_panel);
        notification_panel.setLayout(notification_panelLayout);
        notification_panelLayout.setHorizontalGroup(
            notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        notification_panelLayout.setVerticalGroup(
            notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logout_button))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notification_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notification_label, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(notification_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notification_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout_button))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthly_report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthly_report_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(monthly_report_panel));
    }//GEN-LAST:event_monthly_report_buttonActionPerformed

    private void pay_by_cash_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_by_cash_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(pay_by_cash_panel));
    }//GEN-LAST:event_pay_by_cash_buttonActionPerformed

    private void history_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(history_panel));
    }//GEN-LAST:event_history_buttonActionPerformed

    private void recharge_credit_facility_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recharge_credit_facility_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(recharge_credit_facility_panel));
    }//GEN-LAST:event_recharge_credit_facility_buttonActionPerformed

    private void pay_by_credit_facility_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_by_credit_facility_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(pay_by_credit_facility_panel));
    }//GEN-LAST:event_pay_by_credit_facility_buttonActionPerformed

    private void daily_report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daily_report_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(daily_report_panel));
    }//GEN-LAST:event_daily_report_buttonActionPerformed

    private void return_items_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_items_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(return_item_panel));
    }//GEN-LAST:event_return_items_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        this.dispose();
        LogIn logIn = new LogIn();
        logIn.setVisible(true);
        
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void update_credit_facility_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_credit_facility_buttonActionPerformed
        TreeMap<String, Object> map = ConnectCashier.getCustomerDetails(customer_id_text_field.getText());
        Double  paid_amount = Double.parseDouble(amount_paid_text_field.getText()) + (Double)map.get(Keys.AvailableCredit);
        ConnectCashier.updateCredit(customer_id_text_field.getText(), paid_amount);
        
        map = ConnectCashier.getCustomerDetails(customer_id_text_field.getText());
        String out = "First Name:\t"+map.get(Keys.FirstName)+"\n\nLast Name:\t"+map.get(Keys.LastName)+
                "\n\nAddress:\t"+map.get(Keys.AddressNumber)+
                "\n\t"+map.get(Keys.AddressStreet)+ "\n\t"+map.get(Keys.AddressCity) + "\n\nEmail:\t"+
                map.get(Keys.Email)+"\n\nCredit Limit:\t"+map.get(Keys.CreditLimit)+"\n\nAv. Credit:\t"+
                map.get(Keys.AvailableCredit);
        jTextArea1.setText(out);
    }//GEN-LAST:event_update_credit_facility_buttonActionPerformed

    private void print_pay_by_cash_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_pay_by_cash_billActionPerformed
        try {
            Document document = new Document(PageSize.A4) {};
            PdfWriter.getInstance(document, new FileOutputStream("Bill.pdf"));
            document.open();
            document.add(new Paragraph("One Stop Shop"));
            Image image = null;
            try {
                image = Image.getInstance ("C:\\wamp\\www\\one_stop_shop\\OneStopShop\\src\\Resources\\Cashier\\logo.png");
            } catch (BadElementException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            }
            image.setAbsolutePosition(500f, 770f);
            document.add(image); 
            document.add(new Paragraph(new java.util.Date().toString()));
            document.add(new Paragraph("------------------------------------------------------------"
                    + "---------------------------------------------------------------"));
            document.add(new Paragraph("\n"));
            PdfPTable table = new PdfPTable(5);
            table.setTotalWidth(520);
            table.setLockedWidth(true);
            table.setWidths(new float[]{1, 2, 1,1,1});
            table.addCell("ItemCode");
            table.addCell("Type");
            table.addCell("Amount");
            table.addCell("Cost per item");
            table.addCell("Cost");
            int rowCount = jTable1.getRowCount();
            //System.out.println(rowCount);
            for(int i=0; i<rowCount; i++){
                table.addCell(jTable1.getModel().getValueAt(i, 0).toString());
                table.addCell(jTable1.getModel().getValueAt(i, 1).toString());
                table.addCell(jTable1.getModel().getValueAt(i, 2).toString());
                table.addCell(jTable1.getModel().getValueAt(i, 3).toString());
                table.addCell(jTable1.getModel().getValueAt(i, 4).toString());
            }
            table.setWidthPercentage(100);
            table.setHorizontalAlignment(Element.ALIGN_LEFT);
            document.add(table);
            document.add(new Paragraph("\n"));
            document.add(new Paragraph("                                                            "
                    + "                                                 "
                    + "Total: " +total_text_field.getText()));
            document.add(new Paragraph("------------------------------------------------------------"
                    + "---------------------------------------------------------------"));
            document.close();
            if (Desktop.isDesktopSupported()) {
                try {
                    File myFile = new File("C:\\wamp\\www\\one_stop_shop\\OneStopShop\\Bill.pdf");
                    Desktop.getDesktop().open(myFile);
                } catch (IOException ex) {
                // no application registered for PDFs
                }
            }
        } catch (DocumentException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_pay_by_cash_billActionPerformed

    private void amount_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_text_fieldActionPerformed
        
    }//GEN-LAST:event_amount_text_fieldActionPerformed

    private void item_code_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_code_text_fieldActionPerformed
        amount_text_field.requestFocusInWindow();
    }//GEN-LAST:event_item_code_text_fieldActionPerformed

    private void customer_id_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_id_text_fieldActionPerformed
        TreeMap<String, Object> map = ConnectCashier.getCustomerDetails(customer_id_text_field.getText().substring(0, 6));
        if(map != null){
            String out = "First Name:\t"+map.get(Keys.FirstName)+"\n\nLast Name:\t"+map.get(Keys.LastName)+
                    "\n\nAddress:\t"+map.get(Keys.AddressNumber)+
                    "\n\t"+map.get(Keys.AddressStreet)+ "\n\t"+map.get(Keys.AddressCity) + "\n\nEmail:\t"+
                    map.get(Keys.Email)+"\n\nCredit Limit:\t"+map.get(Keys.CreditLimit)+"\n\nAv. Credit:\t"+
                    map.get(Keys.AvailableCredit);
            jTextArea1.setText(out);
            amount_paid_text_field.requestFocusInWindow();
        }else{
            JOptionPane.showConfirmDialog(null, "Wrong CustomerID", "Warning", JOptionPane.CANCEL_OPTION);
        }

    }//GEN-LAST:event_customer_id_text_fieldActionPerformed

    private void finish_pay_by_cash_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_pay_by_cash_buttonActionPerformed
        
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(home_panel));
    }//GEN-LAST:event_finish_pay_by_cash_buttonActionPerformed

    private void print_pay_by_cash_bill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_pay_by_cash_bill1ActionPerformed
        try {
            Document document = new Document(PageSize.A4) {};
            PdfWriter.getInstance(document, new FileOutputStream("Bill.pdf"));
            document.open();
            document.add(new Paragraph("One Stop Shop"));
            Image image = null;
            try {
                image = Image.getInstance ("C:\\wamp\\www\\one_stop_shop\\OneStopShop\\src\\Resources\\Cashier\\logo.png");
            } catch (BadElementException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
            }
            image.setAbsolutePosition(500f, 770f);
            document.add(image); 
            document.add(new Paragraph(new java.util.Date().toString()));
            document.add(new Paragraph("------------------------------------------------------------"
                    + "---------------------------------------------------------------"));
            document.add(new Paragraph("\n"));
            PdfPTable table = new PdfPTable(5);
            table.setTotalWidth(520);
            table.setLockedWidth(true);
            table.setWidths(new float[]{1, 2, 1,1,1});
            table.addCell("ItemCode");
            table.addCell("Type");
            table.addCell("Amount");
            table.addCell("Cost per item");
            table.addCell("Cost");
            int rowCount = jTable2.getRowCount();
            //System.out.println(rowCount);
            for(int i=0; i<rowCount; i++){
                table.addCell(jTable2.getModel().getValueAt(i, 0).toString());
                table.addCell(jTable2.getModel().getValueAt(i, 1).toString());
                table.addCell(jTable2.getModel().getValueAt(i, 2).toString());
                table.addCell(jTable2.getModel().getValueAt(i, 3).toString());
                table.addCell(jTable2.getModel().getValueAt(i, 4).toString());
            }
            table.setWidthPercentage(100);
            table.setHorizontalAlignment(Element.ALIGN_LEFT);
            document.add(table);
            document.add(new Paragraph("\n"));
            document.add(new Paragraph("                                                            "
                    + "                                                 "
                    + "Total: " +total_text_field1.getText()));
            document.add(new Paragraph("------------------------------------------------------------"
                    + "---------------------------------------------------------------"));
            document.close();
            if (Desktop.isDesktopSupported()) {
                try {
                    File myFile = new File("C:\\wamp\\www\\one_stop_shop\\OneStopShop\\Bill.pdf");
                    Desktop.getDesktop().open(myFile);
                } catch (IOException ex) {
                // no application registered for PDFs
                }
            }
        } catch (DocumentException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CashierView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_pay_by_cash_bill1ActionPerformed

    private void finish_pay_by_cash_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_pay_by_cash_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finish_pay_by_cash_button1ActionPerformed

    private void amount_text_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_text_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_text_field1ActionPerformed

    private void item_code_text_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_code_text_field1ActionPerformed
        amount_text_field1.requestFocusInWindow();
    }//GEN-LAST:event_item_code_text_field1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            
            // Set System L&F
        /*UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());*/
            
            //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel");
            UIManager.setLookAndFeel ( WebLookAndFeel.class.getCanonicalName () );
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CashierView cashier_view = new CashierView();
                cashier_view.setVisible(true);
                cashier_view.notification_label.setText("You are logged in");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_paid_label;
    private javax.swing.JTextField amount_paid_text_field;
    private javax.swing.JFormattedTextField amount_text_field;
    private javax.swing.JFormattedTextField amount_text_field1;
    private javax.swing.JLabel customer_id_label;
    private javax.swing.JFormattedTextField customer_id_text_field;
    private javax.swing.JButton daily_report_button;
    private javax.swing.JPanel daily_report_panel;
    private javax.swing.JButton finish_pay_by_cash_button;
    private javax.swing.JButton finish_pay_by_cash_button1;
    private javax.swing.JButton history_button;
    private javax.swing.JPanel history_panel;
    private javax.swing.JPanel home_panel;
    private javax.swing.JFormattedTextField item_code_text_field;
    private javax.swing.JFormattedTextField item_code_text_field1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton monthly_report_button;
    private javax.swing.JPanel monthly_report_panel;
    private javax.swing.JLabel notification_label;
    private javax.swing.JPanel notification_panel;
    private javax.swing.JButton pay_by_cash_button;
    private javax.swing.JPanel pay_by_cash_panel;
    private javax.swing.JButton pay_by_credit_facility_button;
    private javax.swing.JPanel pay_by_credit_facility_panel;
    private javax.swing.JButton print_pay_by_cash_bill;
    private javax.swing.JButton print_pay_by_cash_bill1;
    private javax.swing.JButton recharge_credit_facility_button;
    private javax.swing.JPanel recharge_credit_facility_panel;
    private javax.swing.JPanel return_item_panel;
    private javax.swing.JButton return_items_button;
    private javax.swing.JFormattedTextField total_text_field;
    private javax.swing.JFormattedTextField total_text_field1;
    private javax.swing.JButton update_credit_facility_button;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getItemCode(){
        return item_code_text_field;
    }
    
    public JTextField getAmount(){
        return amount_text_field;
    }
    
    public JTextField getTotal(){
        return total_text_field;
    }
    
    public JTable getTable(){
        return jTable1;
    }
    
    public JTextField getItemCode_cf(){
        return item_code_text_field1;
    }
    
    public JTextField getAmount_cf(){
        return amount_text_field1;
    }
    
    public JTextField getTotal_cf(){
        return total_text_field1;
    }
    
    public JTable getTable_cf(){
        return jTable2;
    }
    
    public void setTotal(double tot){
        System.out.println("Rs. "+String.valueOf(tot));
        total_text_field.setText("Rs. "+String.valueOf(tot));
        
        item_code_text_field.setText("");
        amount_text_field.setText("");
        item_code_text_field.requestFocusInWindow();
    }
    
    public void setTotal_cf(double tot){
        System.out.println("Rs. "+String.valueOf(tot));
        total_text_field1.setText("Rs. "+String.valueOf(tot));
        
        item_code_text_field1.setText("");
        amount_text_field1.setText("");
        item_code_text_field1.requestFocusInWindow();
    }
    
    public boolean insertRow(String Type, double price){
        double cost = Integer.parseInt(this.getAmount().getText())*price;
                
        DefaultTableModel defaultModel = (DefaultTableModel) jTable1.getModel();  
        defaultModel.addRow(new Object[]{ this.getItemCode().getText(), Type, Integer.parseInt(this.getAmount().getText()), price,cost });  
        JTable newTable = new JTable(defaultModel);  
        jTable1 = newTable;
        return false;
    }
    
    public boolean insertRow_cf(String Type, double price){
        double cost = Integer.parseInt(this.getAmount_cf().getText())*price;
                
        DefaultTableModel defaultModel = (DefaultTableModel) jTable2.getModel();  
        defaultModel.addRow(new Object[]{ this.getItemCode_cf().getText(), Type, Integer.parseInt(this.getAmount_cf().getText()), price,cost });  
        JTable newTable = new JTable(defaultModel);  
        jTable2 = newTable;
        return false;
    }

}
